#!/bin/sh

if [ "x${1}" = "x" ]; then
	echo "usage: makedist [dist-X.X]"
	exit 1
fi
mkdir $1

cp -r NEWS htdocs LGPL makedist README tinymvc $1
vi $1/NEWS $1/README $1/tinymvc/sysfiles/TinyMVC.php
tar -zcvf ${1}.tar.gz $1
zip -r ${1}.zip $1
rm -rf $1
